/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDoubleTouch__factory } from "./IDoubleTouch__factory";
export { ITouch__factory } from "./ITouch__factory";
