import { SignalsItem } from './types';

export const data: SignalsItem[] = [
  {
    asset: 'Uniswap',
    chart: '',
    sentiment: '',
    type: 'type',
    FiveMin: '5min',
    fifteenMin: '15min',
    Hourly: '15min',
    daily: '15min',
    watchList: '15min',
    tradeNow: '15min',
  },
  {
    asset: 'Uniswap',
    chart: '',
    sentiment: '',
    type: 'type',
    FiveMin: '5min',
    fifteenMin: '15min',
    Hourly: '15min',
    daily: '15min',
    watchList: '15min',
    tradeNow: '15min',
  },
  {
    asset: 'Uniswap',
    chart: '',
    sentiment: '',
    type: 'type',
    FiveMin: '5min',
    fifteenMin: '15min',
    Hourly: '15min',
    daily: '15min',
    watchList: '15min',
    tradeNow: '15min',
  },
  {
    asset: 'Uniswap',
    chart: '',
    sentiment: '',
    type: 'type',
    FiveMin: '5min',
    fifteenMin: '15min',
    Hourly: '15min',
    daily: '15min',
    watchList: '15min',
    tradeNow: '15min',
  },
  {
    asset: 'Uniswap',
    chart: '',
    sentiment: '',
    type: 'type',
    FiveMin: '5min',
    fifteenMin: '15min',
    Hourly: '15min',
    daily: '15min',
    watchList: '15min',
    tradeNow: '15min',
  },
  {
    asset: 'Uniswap',
    chart: '',
    sentiment: '',
    type: 'type',
    FiveMin: '5min',
    fifteenMin: '15min',
    Hourly: '15min',
    daily: '15min',
    watchList: '15min',
    tradeNow: '15min',
  },
  {
    asset: 'Uniswap',
    chart: '',
    sentiment: '',
    type: 'type',
    FiveMin: '5min',
    fifteenMin: '15min',
    Hourly: '15min',
    daily: '15min',
    watchList: '15min',
    tradeNow: '15min',
  },
  {
    asset: 'Uniswap',
    chart: '',
    sentiment: '',
    type: 'type',
    FiveMin: '5min',
    fifteenMin: '15min',
    Hourly: '15min',
    daily: '15min',
    watchList: '15min',
    tradeNow: '15min',
  },
  {
    asset: 'Uniswap',
    chart: '',
    sentiment: '',
    type: 'type',
    FiveMin: '5min',
    fifteenMin: '15min',
    Hourly: '15min',
    daily: '15min',
    watchList: '15min',
    tradeNow: '15min',
  },

];
