import sentiment from '@option-blitz/libs/assets/images/sentiment.png';
import aud_jpy from '@option-blitz/libs/assets/images/countries/AUD-JPY.png';
import aud_usd from '@option-blitz/libs/assets/images/countries/AUD-USD.png';
import eur_aud from '@option-blitz/libs/assets/images/countries/EUR-AUD.png';
import eur_cad from '@option-blitz/libs/assets/images/countries/EUR-CAD.png';
import eur_chf from '@option-blitz/libs/assets/images/countries/EUR-CHF.png';
import eur_gpb from '@option-blitz/libs/assets/images/countries/EUR-GBP.png';
import eur_jpy from '@option-blitz/libs/assets/images/countries/EUR-JPY.png';
import eur_usd from '@option-blitz/libs/assets/images/countries/EUR-USD.png';
import gbp_jpy from '@option-blitz/libs/assets/images/countries/GBP-JPY.png';
import gbp_usd from '@option-blitz/libs/assets/images/countries/GBP-USD.png';
import usd_cad from '@option-blitz/libs/assets/images/countries/USD-CAD.png';
import usd_jpy from '@option-blitz/libs/assets/images/countries/USD-JPY.png';
import { Forex } from './types';

export const money: Forex [] = [
  {
    assets: 'XAU/USD',
    icon: aud_jpy,
    valute: 'AUD/JPY',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: aud_usd,
    valute: 'AUD/USD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: eur_aud,
    valute: 'EUR/AUD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: eur_cad,
    valute: 'EUR/CAD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: eur_chf,
    valute: 'EUR/CHF',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
];
export const data: Forex [] = [
  {
    assets: 'XAU/USD',
    icon: aud_jpy,
    valute: 'AUD/JPY',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: aud_usd,
    valute: 'AUD/USD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: eur_aud,
    valute: 'EUR/AUD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: eur_cad,
    valute: 'EUR/CAD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: eur_chf,
    valute: 'EUR/CHF',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: eur_gpb,
    valute: 'EUR/GPB',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: eur_jpy,
    valute: 'EUR/JPY',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: eur_usd,
    valute: 'EUR/USD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: gbp_jpy,
    valute: 'GBP/JPY',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: gbp_usd,
    valute: 'GPB/USD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: usd_cad,
    valute: 'USD/CAD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: usd_jpy,
    valute: 'USD/JPY',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
];
export const dara = {
  Forex: [
    {
      assets: {
        icon: 'icon_url',
        currency: 'XAU/USD',
        value: 1.282815,
      },
      profit1: 84,
      profit2: 84,
      profit3: 84,
      profit4: 84,
      profit5: 70,
      profit6: 70,
      sentiment: {
        current: 10,
        total: 126,
      },
      chart: [
        {
          1: 100,
          2: 50,
          3: 40,
        },
      ],
      watchlist: [],
    },
    {
      assets: {
        icon: 'icon_url',
        currency: 'XAU/UAH',
        value: 0.363637,
      },
      profit1: 24,
      profit2: 81,
      profit3: 22,
      profit4: 44,
      profit5: 56,
      profit6: 12,
      sentiment: {
        current: 5,
        total: 94,
      },
      chart: [
        {
          1: 100,
          2: 50,
          3: 40,
        },
      ],
      watchlist: [],
    },
  ],
  Crypto: [
    {
      assets: {
        icon: 'icon_url',
        currency: 'XAU/UAH',
        value: 0.363637,
      },
      profit1: 24,
      profit2: 81,
      profit3: 22,
      profit4: 44,
      profit5: 56,
      profit6: 12,
      sentiment: {
        current: 5,
        total: 94,
      },
      chart: [
        {
          1: 100,
          2: 50,
          3: 40,
        },
      ],
      watchlist: [],
    },
  ],
};

export const menu = [{ id: 1, name: 'Forex' }, { id: 2, name: 'Crypto' }];
