import gold from '@option-blitz/libs/assets/images/metals/gold.svg';
import cup from '@option-blitz/libs/assets/images/metals/Copper-USD.svg';
import silv from '@option-blitz/libs/assets/images/metals/silver.svg';
import steel from '@option-blitz/libs/assets/images/metals/steel.svg';
import plat from '@option-blitz/libs/assets/images/metals/platina.svg';
import sentiment from '@option-blitz/libs/assets/images/sentiment.png';
import { Forex } from './types';

export const metals: Forex [] = [
  {
    assets: 'XAU/USD',
    icon: gold,
    valute: 'XAU/USD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: steel,
    valute: 'XPT/USD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: silv,
    valute: 'XAG/USD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: cup,
    valute: 'COOPER/USD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },
  {
    assets: 'XAU/USD',
    icon: plat,
    valute: 'XPD/USD',
    course: '1.282815',
    profit1: '84%',
    profit2: '84%',
    profit3: '84%',
    profit4: '84%',
    profit5: '70%',
    profit6: '70%',
    sentiment,
    chart: '\'http://www.w3.org/2000/svg\'',
    watchlist: [],
    tradeNow: [],
  },

];
