export type Forex = {
  assets: string,
  icon: string,
  valute: string,
  course: string,
  profit1: string,
  profit2: string,
  profit3: string,
  profit4: string,
  profit5: string,
  profit6: string,
  sentiment: string,
  chart: string,
  watchlist: [],
  tradeNow: [],
};
