/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RewardsDistributionRecipient } from "./RewardsDistributionRecipient";
export type { StakingRewards } from "./StakingRewards";
