/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export interface KYCStateInterface extends utils.Interface {
  functions: {
    "ACCEPTED()": FunctionFragment;
    "FIRST_VALUE()": FunctionFragment;
    "LAST_VALUE()": FunctionFragment;
    "REJECTED()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "ACCEPTED"
      | "FIRST_VALUE"
      | "LAST_VALUE"
      | "REJECTED"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "ACCEPTED", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "FIRST_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LAST_VALUE",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "REJECTED", values?: undefined): string;

  decodeFunctionResult(functionFragment: "ACCEPTED", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "FIRST_VALUE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "LAST_VALUE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "REJECTED", data: BytesLike): Result;

  events: {};
}

export interface KYCState extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: KYCStateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    ACCEPTED(overrides?: CallOverrides): Promise<[BigNumber]>;

    FIRST_VALUE(overrides?: CallOverrides): Promise<[BigNumber]>;

    LAST_VALUE(overrides?: CallOverrides): Promise<[BigNumber]>;

    REJECTED(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  ACCEPTED(overrides?: CallOverrides): Promise<BigNumber>;

  FIRST_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

  LAST_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

  REJECTED(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    ACCEPTED(overrides?: CallOverrides): Promise<BigNumber>;

    FIRST_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

    LAST_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

    REJECTED(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    ACCEPTED(overrides?: CallOverrides): Promise<BigNumber>;

    FIRST_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

    LAST_VALUE(overrides?: CallOverrides): Promise<BigNumber>;

    REJECTED(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ACCEPTED(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    FIRST_VALUE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    LAST_VALUE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REJECTED(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
