/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IFormulasInterface extends utils.Interface {
  functions: {
    "adj_coef(int128,int128)": FunctionFragment;
    "americanRisk(bool,uint256,int128,int128,int128)": FunctionFragment;
    "american_collateral_call_accurate(int128,int128,int128,uint256)": FunctionFragment;
    "american_collateral_call_put(int128,int128,int128,uint256)": FunctionFragment;
    "american_collateral_put_accurate(int128,int128,int128,uint256)": FunctionFragment;
    "american_price_call_put(int128,int128,int128)": FunctionFragment;
    "american_worse_price_call(int128,int128,uint256)": FunctionFragment;
    "american_worse_price_put(int128,int128,uint256)": FunctionFragment;
    "binary_call(int128,int128)": FunctionFragment;
    "binary_put(int128,int128)": FunctionFragment;
    "burnBlxIncrease(uint256,int128,uint256)": FunctionFragment;
    "option_american_call(int128,int128,int128,int128)": FunctionFragment;
    "option_american_put(int128,int128,int128,int128)": FunctionFragment;
    "option_double_no_touch(int128,int128,int128,int128,int128)": FunctionFragment;
    "option_double_touch(int128,int128,int128,int128,int128)": FunctionFragment;
    "option_no_touch_call(int128,int128,int128,int128)": FunctionFragment;
    "option_no_touch_put(int128,int128,int128,int128)": FunctionFragment;
    "option_touch_call(int128,int128,int128,int128)": FunctionFragment;
    "option_touch_put(int128,int128,int128,int128)": FunctionFragment;
    "setFactorF(int128)": FunctionFragment;
    "stakeBlxIncrease(uint256,int128,uint256,uint256)": FunctionFragment;
    "turbo_barrier(int128,int128,bool)": FunctionFragment;
    "turbo_notional(int128,int128,int128,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "adj_coef"
      | "americanRisk"
      | "american_collateral_call_accurate"
      | "american_collateral_call_put"
      | "american_collateral_put_accurate"
      | "american_price_call_put"
      | "american_worse_price_call"
      | "american_worse_price_put"
      | "binary_call"
      | "binary_put"
      | "burnBlxIncrease"
      | "option_american_call"
      | "option_american_put"
      | "option_double_no_touch"
      | "option_double_touch"
      | "option_no_touch_call"
      | "option_no_touch_put"
      | "option_touch_call"
      | "option_touch_put"
      | "setFactorF"
      | "stakeBlxIncrease"
      | "turbo_barrier"
      | "turbo_notional"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "adj_coef",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "americanRisk",
    values: [
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "american_collateral_call_accurate",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "american_collateral_call_put",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "american_collateral_put_accurate",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "american_price_call_put",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "american_worse_price_call",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "american_worse_price_put",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "binary_call",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "binary_put",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "burnBlxIncrease",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "option_american_call",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "option_american_put",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "option_double_no_touch",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "option_double_touch",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "option_no_touch_call",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "option_no_touch_put",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "option_touch_call",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "option_touch_put",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setFactorF",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeBlxIncrease",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "turbo_barrier",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "turbo_notional",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "adj_coef", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "americanRisk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "american_collateral_call_accurate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "american_collateral_call_put",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "american_collateral_put_accurate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "american_price_call_put",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "american_worse_price_call",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "american_worse_price_put",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "binary_call",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "binary_put", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnBlxIncrease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "option_american_call",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "option_american_put",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "option_double_no_touch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "option_double_touch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "option_no_touch_call",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "option_no_touch_put",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "option_touch_call",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "option_touch_put",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFactorF", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeBlxIncrease",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "turbo_barrier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "turbo_notional",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IFormulas extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFormulasInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    adj_coef(
      _r1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    americanRisk(
      _optionType: PromiseOrValue<boolean>,
      _timeOption: PromiseOrValue<BigNumberish>,
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    american_collateral_call_accurate(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    american_collateral_call_put(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    american_collateral_put_accurate(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    american_price_call_put(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    american_worse_price_call(
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    american_worse_price_put(
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    binary_call(
      betUser: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    binary_put(
      betUser: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    burnBlxIncrease(
      blxAmount: PromiseOrValue<BigNumberish>,
      blxPrice: PromiseOrValue<BigNumberish>,
      totalLiquidity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    option_american_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    option_american_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    option_double_no_touch(
      S: PromiseOrValue<BigNumberish>,
      KH: PromiseOrValue<BigNumberish>,
      KL: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    option_double_touch(
      S: PromiseOrValue<BigNumberish>,
      KH: PromiseOrValue<BigNumberish>,
      KL: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    option_no_touch_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    option_no_touch_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    option_touch_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    option_touch_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setFactorF(
      _fFactor: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    stakeBlxIncrease(
      blxAmount: PromiseOrValue<BigNumberish>,
      blxPrice: PromiseOrValue<BigNumberish>,
      totalLiquidity: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    turbo_barrier(
      leverage: PromiseOrValue<BigNumberish>,
      assetPrice: PromiseOrValue<BigNumberish>,
      optionType: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    turbo_notional(
      barrier: PromiseOrValue<BigNumberish>,
      assetPrice: PromiseOrValue<BigNumberish>,
      investment: PromiseOrValue<BigNumberish>,
      optionType: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  adj_coef(
    _r1: PromiseOrValue<BigNumberish>,
    _r2: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  americanRisk(
    _optionType: PromiseOrValue<boolean>,
    _timeOption: PromiseOrValue<BigNumberish>,
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  american_collateral_call_accurate(
    N_lot: PromiseOrValue<BigNumberish>,
    S0: PromiseOrValue<BigNumberish>,
    hv: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  american_collateral_call_put(
    N_lot: PromiseOrValue<BigNumberish>,
    S0: PromiseOrValue<BigNumberish>,
    hv: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  american_collateral_put_accurate(
    N_lot: PromiseOrValue<BigNumberish>,
    S0: PromiseOrValue<BigNumberish>,
    hv: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  american_price_call_put(
    N_lot: PromiseOrValue<BigNumberish>,
    S0: PromiseOrValue<BigNumberish>,
    hv: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  american_worse_price_call(
    S0: PromiseOrValue<BigNumberish>,
    hv: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  american_worse_price_put(
    S0: PromiseOrValue<BigNumberish>,
    hv: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  binary_call(
    betUser: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  binary_put(
    betUser: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  burnBlxIncrease(
    blxAmount: PromiseOrValue<BigNumberish>,
    blxPrice: PromiseOrValue<BigNumberish>,
    totalLiquidity: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  option_american_call(
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    betUser: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  option_american_put(
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    betUser: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  option_double_no_touch(
    S: PromiseOrValue<BigNumberish>,
    KH: PromiseOrValue<BigNumberish>,
    KL: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    betUser: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  option_double_touch(
    S: PromiseOrValue<BigNumberish>,
    KH: PromiseOrValue<BigNumberish>,
    KL: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    betUser: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  option_no_touch_call(
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    betUser: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  option_no_touch_put(
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    betUser: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  option_touch_call(
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    betUser: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  option_touch_put(
    S: PromiseOrValue<BigNumberish>,
    K: PromiseOrValue<BigNumberish>,
    _hv: PromiseOrValue<BigNumberish>,
    betUser: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setFactorF(
    _fFactor: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  stakeBlxIncrease(
    blxAmount: PromiseOrValue<BigNumberish>,
    blxPrice: PromiseOrValue<BigNumberish>,
    totalLiquidity: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  turbo_barrier(
    leverage: PromiseOrValue<BigNumberish>,
    assetPrice: PromiseOrValue<BigNumberish>,
    optionType: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  turbo_notional(
    barrier: PromiseOrValue<BigNumberish>,
    assetPrice: PromiseOrValue<BigNumberish>,
    investment: PromiseOrValue<BigNumberish>,
    optionType: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    adj_coef(
      _r1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    americanRisk(
      _optionType: PromiseOrValue<boolean>,
      _timeOption: PromiseOrValue<BigNumberish>,
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_collateral_call_accurate(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_collateral_call_put(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_collateral_put_accurate(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_price_call_put(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_worse_price_call(
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_worse_price_put(
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    binary_call(
      betUser: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    binary_put(
      betUser: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burnBlxIncrease(
      blxAmount: PromiseOrValue<BigNumberish>,
      blxPrice: PromiseOrValue<BigNumberish>,
      totalLiquidity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_american_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_american_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_double_no_touch(
      S: PromiseOrValue<BigNumberish>,
      KH: PromiseOrValue<BigNumberish>,
      KL: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_double_touch(
      S: PromiseOrValue<BigNumberish>,
      KH: PromiseOrValue<BigNumberish>,
      KL: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_no_touch_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_no_touch_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_touch_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_touch_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFactorF(
      _fFactor: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    stakeBlxIncrease(
      blxAmount: PromiseOrValue<BigNumberish>,
      blxPrice: PromiseOrValue<BigNumberish>,
      totalLiquidity: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    turbo_barrier(
      leverage: PromiseOrValue<BigNumberish>,
      assetPrice: PromiseOrValue<BigNumberish>,
      optionType: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    turbo_notional(
      barrier: PromiseOrValue<BigNumberish>,
      assetPrice: PromiseOrValue<BigNumberish>,
      investment: PromiseOrValue<BigNumberish>,
      optionType: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    adj_coef(
      _r1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    americanRisk(
      _optionType: PromiseOrValue<boolean>,
      _timeOption: PromiseOrValue<BigNumberish>,
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_collateral_call_accurate(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_collateral_call_put(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_collateral_put_accurate(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_price_call_put(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_worse_price_call(
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    american_worse_price_put(
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    binary_call(
      betUser: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    binary_put(
      betUser: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burnBlxIncrease(
      blxAmount: PromiseOrValue<BigNumberish>,
      blxPrice: PromiseOrValue<BigNumberish>,
      totalLiquidity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_american_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_american_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_double_no_touch(
      S: PromiseOrValue<BigNumberish>,
      KH: PromiseOrValue<BigNumberish>,
      KL: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_double_touch(
      S: PromiseOrValue<BigNumberish>,
      KH: PromiseOrValue<BigNumberish>,
      KL: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_no_touch_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_no_touch_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_touch_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    option_touch_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setFactorF(
      _fFactor: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    stakeBlxIncrease(
      blxAmount: PromiseOrValue<BigNumberish>,
      blxPrice: PromiseOrValue<BigNumberish>,
      totalLiquidity: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    turbo_barrier(
      leverage: PromiseOrValue<BigNumberish>,
      assetPrice: PromiseOrValue<BigNumberish>,
      optionType: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    turbo_notional(
      barrier: PromiseOrValue<BigNumberish>,
      assetPrice: PromiseOrValue<BigNumberish>,
      investment: PromiseOrValue<BigNumberish>,
      optionType: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adj_coef(
      _r1: PromiseOrValue<BigNumberish>,
      _r2: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    americanRisk(
      _optionType: PromiseOrValue<boolean>,
      _timeOption: PromiseOrValue<BigNumberish>,
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    american_collateral_call_accurate(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    american_collateral_call_put(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    american_collateral_put_accurate(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    american_price_call_put(
      N_lot: PromiseOrValue<BigNumberish>,
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    american_worse_price_call(
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    american_worse_price_put(
      S0: PromiseOrValue<BigNumberish>,
      hv: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    binary_call(
      betUser: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    binary_put(
      betUser: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    burnBlxIncrease(
      blxAmount: PromiseOrValue<BigNumberish>,
      blxPrice: PromiseOrValue<BigNumberish>,
      totalLiquidity: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    option_american_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    option_american_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    option_double_no_touch(
      S: PromiseOrValue<BigNumberish>,
      KH: PromiseOrValue<BigNumberish>,
      KL: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    option_double_touch(
      S: PromiseOrValue<BigNumberish>,
      KH: PromiseOrValue<BigNumberish>,
      KL: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    option_no_touch_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    option_no_touch_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    option_touch_call(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    option_touch_put(
      S: PromiseOrValue<BigNumberish>,
      K: PromiseOrValue<BigNumberish>,
      _hv: PromiseOrValue<BigNumberish>,
      betUser: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setFactorF(
      _fFactor: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    stakeBlxIncrease(
      blxAmount: PromiseOrValue<BigNumberish>,
      blxPrice: PromiseOrValue<BigNumberish>,
      totalLiquidity: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    turbo_barrier(
      leverage: PromiseOrValue<BigNumberish>,
      assetPrice: PromiseOrValue<BigNumberish>,
      optionType: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    turbo_notional(
      barrier: PromiseOrValue<BigNumberish>,
      assetPrice: PromiseOrValue<BigNumberish>,
      investment: PromiseOrValue<BigNumberish>,
      optionType: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
