/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as americanOption from "./American_Option";
export type { americanOption };
import type * as binary from "./Binary";
export type { binary };
import type * as iAccessContractSol from "./IAccessContract.sol";
export type { iAccessContractSol };
import type * as iChangeRewardSol from "./IChangeReward.sol";
export type { iChangeRewardSol };
import type * as sale from "./Sale";
export type { sale };
import type * as touch from "./Touch";
export type { touch };
import type * as turbo from "./Turbo";
export type { turbo };
import type * as stakingrewards from "./stakingrewards";
export type { stakingrewards };
export type { IAffiliate } from "./IAffiliate";
export type { IAffiliateNew } from "./IAffiliateNew";
export type { IBlxToken } from "./IBlxToken";
export type { IBroker } from "./IBroker";
export type { IFormulas } from "./IFormulas";
export type { ISimpleOracle } from "./ISimpleOracle";
export type { IStaking } from "./IStaking";
export type { IStakingContract } from "./IStakingContract";
export type { ITreasury } from "./ITreasury";
