export enum AffiliateActionTypes {
  GetAllData = 'AFFILIATE.GET_ALL_DATA',
  GetAllDataSuccess = 'AFFILIATE.GET_ALL_DATA_SUCCESS',
  GetAllDataFail = 'AFFILIATE.GET_ALL_FAIL',

  GetAllPromoCodes = 'AFFILIATE.GET_ALL_PROMO_CODES',
  GetAllPromoCodesSuccess = 'AFFILIATE.GET_ALL_PROMO_CODES_SUCCESS',
  GetAllPromoCodesFail = 'AFFILIATE.GET_ALL_PROMO_CODES_FAIL',

  CreatePromoCodes = 'AFFILIATE.CREATE_PROMO_CODES',
  CreatePromoCodesSuccess = 'AFFILIATE.CREATE_PROMO_CODES_SUCCESS',
  CreatePromoCodesFail = 'AFFILIATE.CREATE_PROMO_CODES_FAIL',

  DeletePromoCodes = 'AFFILIATE.DELETE_PROMO_CODES',
  DeletePromoCodesSuccess = 'AFFILIATE.DELETE_PROMO_CODES_SUCCESS',
  DeletePromoCodesFail = 'AFFILIATE.DELETE_PROMO_CODES_FAIL',

  UpdatePromoCodes = 'AFFILIATE.UPDATE_PROMO_CODES',
  UpdatePromoCodesSuccess = 'AFFILIATE.UPDATE_PROMO_CODE_SUCCESS',
  UpdatePromoCodesFail = 'AFFILIATE.UPDATE_PROMO_CODE_FAIL',

  GetCampaigns = 'AFFILIATE.GET_CAMPAIGNS',
  GetCampaignsSuccess = 'AFFILIATE.GET_CAMPAIGNS_SUCCESS',
  GetCampaignsFail = 'AFFILIATE.GET_CAMPAIGNS_FAIL',

  AddCampaigns = 'AFFILIATE.ADD_CAMPAIGNS',
  AddCampaignsSuccess = 'AFFILIATE.ADD_CAMPAIGNS_SUCCESS',
  AddCampaignsFail = 'AFFILIATE.ADD_CAMPAIGNS_FAIL',

  UpdateCampaigns = 'AFFILIATE.UPDATE_CAMPAIGNS',
  UpdateCampaignsSuccess = 'AFFILIATE.UPDATE_CAMPAIGNS_SUCCESS',
  UpdateCampaignsFail = 'AFFILIATE.UPDATE_CAMPAIGNS_FAIL',

  DeleteCampaigns = 'AFFILIATE.DELETE_CAMPAIGNS',
  DeleteCampaignsSuccess = 'AFFILIATE.DELETE_CAMPAIGNS_SUCCESS',
  DeleteCampaignsFail = 'AFFILIATE.DELETE_CAMPAIGNS_FAIL',

  GetTHXCampaigns = 'AFFILIATE.GET_THX_CAMPAIGNS',
  GetTHXCampaignsSuccess = 'AFFILIATE.GET_THX_CAMPAIGNS_SUCCESS',
  GetTHXCampaignsFail = 'AFFILIATE.GET_THX_CAMPAIGNS_FAIL',

  AddTHXCampaigns = 'AFFILIATE.ADD_THX_CAMPAIGNS',
  AddTHXCampaignsSuccess = 'AFFILIATE.ADD_THX_CAMPAIGNS_SUCCESS',
  AddTHXCampaignsFail = 'AFFILIATE.ADD_THX_CAMPAIGNS_FAIL',

  UpdateTHXCampaigns = 'AFFILIATE.UPDATE_THX_CAMPAIGNS',
  UpdateTHXCampaignsSuccess = 'AFFILIATE.UPDATE_THX_CAMPAIGNS_SUCCESS',
  UpdateTHXCampaignsFail = 'AFFILIATE.UPDATE_THX_CAMPAIGNS_FAIL',

  DeleteTHXCampaigns = 'AFFILIATE.DELETE_THX_CAMPAIGNS',
  DeleteTHXCampaignsSuccess = 'AFFILIATE.DELETE_THX_CAMPAIGNS_SUCCESS',
  DeleteTHXCampaignsFail = 'AFFILIATE.DELETE_THX_FAIL',
}
