/* eslint-disable */
import {Promo} from "./typespromo";

export const tiket: Promo [] = [
    {
        number: '1',
        promocode: 'W7JON1Yyb7JmXHLu/M8wPo',
        bonus: '25%',
        mindep: '$55',
        createon: '2021-04-27',
        valid: '2021-04-27',
        numactiv: '13',
        activpergroup: 'Unlimited',
        actions: '',
    },
    {
        number: '2',
        promocode: 'W7JON1Yyb7JmXHLu/M8wPo',
        bonus: '15%',
        mindep: '$40',
        createon: '2021-04-27',
        valid: '2021-04-27',
        numactiv: '6',
        activpergroup: '6',
        actions: '',
    },
    {
        number: '3',
        promocode: 'W7JON1Yyb7JmXHLu/M8wPo',
        bonus: '34%',
        mindep: '$65',
        createon: '2021-04-27',
        valid: '2021-04-27',
        numactiv: '0',
        activpergroup: 'Unlimited',
        actions: '',
    },
    {
        number: '4',
        promocode: 'W7JON1Yyb7JmXHLu/M8wPo',
        bonus: '12%',
        mindep: '$34',
        createon: '2021-04-27',
        valid: '2021-04-27',
        numactiv: '10',
        activpergroup: 'Unlimited',
        actions: '',
    },
    {
        number: '5',
        promocode: 'W7JON1Yyb7JmXHLu/M8wPo',
        bonus: '5%',
        mindep: '$25',
        createon: '2021-04-27',
        valid: '2021-04-27',
        numactiv: '0',
        activpergroup: 'Unlimited',
        actions: '',
    },
    {
        number: '6',
        promocode: 'W7JON1Yyb7JmXHLu/M8wPo',
        bonus: '2%',
        mindep: '$15',
        createon: '2021-04-27',
        valid: '2021-04-27',
        numactiv: '50',
        activpergroup: 'Unlimited',
        actions: '',
    },

]