/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  OptionBase,
  OptionBaseInterface,
} from "../../../contracts/option/OptionBase";

const _abi = [
  {
    inputs: [],
    name: "DECIMALS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MAX_DURATION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "MIN_DURATION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "investment",
        type: "uint256",
      },
      {
        internalType: "int128",
        name: "optionPrice",
        type: "int128",
      },
      {
        internalType: "int128",
        name: "factor",
        type: "int128",
      },
    ],
    name: "calculateBinaryPayoff",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_timeDiff",
        type: "uint256",
      },
    ],
    name: "ensureCorrectDuration",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_timeOpen",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_timeClose",
        type: "uint256",
      },
    ],
    name: "ensureCorrectTimes",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "xNotional",
    outputs: [
      {
        internalType: "int128",
        name: "",
        type: "int128",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class OptionBase__factory {
  static readonly abi = _abi;
  static createInterface(): OptionBaseInterface {
    return new utils.Interface(_abi) as OptionBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): OptionBase {
    return new Contract(address, _abi, signerOrProvider) as OptionBase;
  }
}
