/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRewardsDistributionRecipient } from "./IRewardsDistributionRecipient";
export type { IStakingRewards } from "./IStakingRewards";
